### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by yufeidu** [embedded-sec/BenchIoT#1]
I am having trouble building the benchmarks. Here are the issues I ran into:

- When creating makefile for benchmarks, I used `mbed export -m EVAL_F469NI -i GCC_ARM --profile iot2_debug` command from the README, but mbed threw error: `ImportError: cannot import name epoxy`. I had to remove epoxy and scfi from import to generate the Makefile. 
- After Makefile was generated, I used `make -j4 BOARD=EVAL_F469NI IOT2_ALL=1 CUSTOM_BIN_SUFFIX=--baseline iot2benchmark` command from the README to build benchmark. However, I got this error from the compiler: `/home/user1/projects/BenchIoT/BenchIoT/lib/IoT2/IoT2Lib.c: In function 'iot2SVCHandler':
/home/user1/projects/BenchIoT/BenchIoT/lib/IoT2/IoT2Lib.c:691:5: error: missing ')' in expression
 #if ((IoT2_OS_BENCHMARKS == 0 )
make[1]: *** [/home/user1/projects/BenchIoT/BenchIoT/benchmarks/mbed-benchmarks/bootloader/Makefile:646: IoT2/IoT2Lib.o] Error `. I removed the left parenthesis and was able to compile, but the linker failed with a lot of multiple definition of function errors. 

Here is my platform:

- Ubuntu 19.04
- arm-none-eabi-gcc 7.3.1
- mbed-cli 1.10.0
- Python 2.7.16

I also tried using changing mbed build type to `sw4stm32` and importing the benchmark to System Workbench (Eclipse). However, the Eclipse project is missing a lot of includes, and I believe it is not building IoT2 library. 

Finally, I would like to know how to add support for other boards. I am currently using DISCO_L475VG_IOT01A, and the HAL library of this board doesn't seem to have eth related source files. This board does not have ethernet support but does have Wi-Fi. 

Thank you!

**Comment by nalmakhd** [comment]
Hi @LeveyLeonhardt ,

Please pull the latest commit (https://github.com/embedded-sec/BenchIoT/commit/d4dea4ccb5458656f11c400f051a8ecebef204f1). There were missing files needed by mbed-cli and some typos apparently. I just tried pulling again and building one of the benchmarks (i.e., smart-locker) and the binary was built without issues. My platform was:

-  Ubuntu 14.04
- arm-none-eabi-gcc 7.3.1
- mbed-cli 1.7.5
- python 2.7.6

If you are using a different benchmark please let me know. It will help to specify whether you are building the benchmarks with or without an OS. Please let me know if you face any further issue.

> I also tried using changing mbed build type to sw4stm32 and importing the benchmark to System Workbench (Eclipse)
  
Currently the runtime library is only added for the makefile option. You can modify `sw4stm32` template similar to what is done in `os-lib/mbed-os/tools/export/makefile/Makefile.tmpl`


> Finally, I would like to know how to add support for other boards. I am currently using DISCO_L475VG_IOT01A, and the HAL library of this board doesn't seem to have eth related source files. This board does not have ethernet support but does have Wi-Fi.

Please check `IoT2/IoT2-mbed-wrappers/IoT2_wrappers/tcp/`. If you are using the OS then look into the mbed-os folder, if bare-metal look into the mbed-sdk folder. When the benchmarks are using TCP the wrapper functions are found in the `iot2TCP.h` and `iot2TCP.cpp`. Modify those to your WiFi library but you will need also to modify the calls to these functions in the benchmarks themselves. Also you will need to add the configuration of your board to `IoT2_Config` files.


I hope this helps!

**Comment by yufeidu** [comment]
Hi @nalmakhd,

Thank you for your reply and sorry for my late response. With the latest commit I can now build the benchmarks correctly. 

Thanks again!
